# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MeltingCon
email: meltingcon.kr@gmail.com
description: MeltingCon Community Alliance
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://meltingcon.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Usernames and API Keys
github_username: meltingcon

# Event Sponsors
members:
  - name: GoDev
    url: #
    desc: >
      (설명)
  - name: 데이터그램
    url: https://www.facebook.com/groups/datergram/
    desc: >
      (설명)
  - name: 모여서 각자 코딩하는 모임
    url: https://www.facebook.com/groups/mogaco/
    desc: >
      (설명)
  - name: Vue.js Korea
    url: https://www.facebook.com/groups/vuejs.korea/about/
    desc: >
      Vue.js는 쉽고 빠르게 결과물을 낼 수 있는 JavaScript 프레임워크입니다. Vue.js Korea는 2016년 12월에 생긴 페이스북 그룹으로 시작해, 현재는 슬랙과 오프라인 모임에서도 다양한 배경의 사용자가 경험담을 공유하며 성장하고 있습니다. 
  - name: 스파크 사용자 모임
    url: https://www.facebook.com/groups/sparkkoreauser/
    desc: >
      (설명)
  - name: C++ 사용자 그룹
    url: https://www.facebook.com/groups/cppkorea/
    desc: >
      (설명)
  - name: 우분투 한국 커뮤니티
    url: https://www.ubuntu-kr.org/
    desc: >
      데비안 기반의 가장 대중적인 리눅스 배포판인 우분투(Ubuntu)에 대해서 다루는 커뮤니티 입니다.
      우분투를 쓰거나, 개발하거나, 들어봤거나 또는 관심있는 모든 사람들을 위한 곳입니다.
      2005년부터 활동을 해 오고 있으며, 우분투를 개발한 캐노니컬(Canonical) 로 부터 공식 지역 커뮤니티 인증을 받은 커뮤니티 입니다.
      서울, 대전 지역을 중심으로 타 지역으로도 확장을 해 나가며 세미나와 워크샵 그리고 스터디 등 다양한 오프라인 활동을 하고 있습니다.
      온라인 활동은 포럼, 페이스북, Slack, IRC, 메일링 리스트 등 다양한 채널을 통해 이뤄지고 있습니다.
  - name: OpenStack 한국 커뮤니티
    url: http://openstack.or.kr/
    desc: >
      오픈스택 (OpenStack)은 클라우드 관리 플랫폼을 구축하기 위한 오픈 소스 소프트웨어 프로젝트로,
      개별적으로 설치하는 6개의 코어 및 19개의 선택 컴포넌트들을 서로 유기적으로 연동하여 직접 클라우드를 구성할 수 있습니다.
      2010년 7월 Rackspace사와 NASA로 부터 시작한 이후, 전 세계 179개 국가로부터 50,000명이 넘는 커뮤니티 회원이 참여 및 기여를 통해
      (2016년 7월 통계) 꾸준히 성장하고 있습니다. 오픈스택 한국 커뮤니티는 공식 사용자 그룹으로서 다양한 정기 세미나, 스터디 활동, 
      번역팀 활동을 비롯하여 페이스북, 메일링리스트, IRC, Slack 등 여러 커뮤니케이션 채널을 통해 많은 
      오픈스택 유저 및 관심있는 분들과 활발히 활동하고 있습니다.
  - name: 코딩이랑 무관합니다만,
    url: https://www.facebook.com/groups/System.out.Coding/
    desc: >
      우리는 생활코딩에 물으면 대답해줄거 같은 컴퓨터 관련 질문이지만 코딩관련 질문이 아닐때 약속이라도 한듯 "코딩이랑 무관합니다만" 이라는 어두로 시작을 합니다. 
      그래서 이런 질문들만 주고받는 곳을 따로 만들면 어떨까 하는 생각에 코딩이랑 무관합니다만, 그룹을 재미로 한번 만들어봤습니다.  
  - name: 한국 Azure 사용자 그룹
    url: https://krazure.com/
    desc: >
      (설명)
  - name: 한국 Surface 사용자모임
    url: https://www.facebook.com/groups/SurfaceKorea/about/
    desc: >
      (설명)
  - name: Seoul.js
    url: https://seoul.js.org/
    desc: >
      (설명)
  - name: Kubernetes Korea Group
    url: https://www.facebook.com/groups/k8skr/
    desc: >
      (설명)
# license
owner: "MeltingCon Community Alliance"
code_license: "MIT"
copyright: Copyright (c) 2018 MeltingCon Community Alliance All Rights Reserved.
content_license: "CC BY-SA 4.0"


# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
